apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "process-service.fullname" . }}
data:
  application.properties: |
    spring.kafka.bootstrap-servers={{ .Values.kafka.bootstrapServers }}
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
    spring.kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    server.port=8080
    topic.name={{ .Values.kafka.topicName }}
